name: 🚀 Auto Cool Level Generator

on:
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes
  workflow_dispatch:

jobs:
  generate-level:
    name: 🌟 Generate Cool Level
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v4

      - name: ✨⭐️🧡 Epic Level Unlocked Banner
        run: |
          echo ""
          echo "╔═════════════════════════════════════════════╗"
          echo "║"
          echo "║   🎉⭐️🧡 ＬＥＶＥＬ   ＵＮＬＯＣＫＥＤ ! 🧡⭐️🎉"
          echo "║      ✦✦✦  THE GATE TO GLORY OPENS  ✦✦✦"
          echo "║"
          echo "║   🚀🔥💎 ＮＥＷ   ＣＯＯＬ   ＬＥＶＥＬ 💎🔥🚀"
          echo "║      ✦✦✦  UNLEASH YOUR NEXT POWER!  ✦✦✦"
          echo "║"
          echo "╚═════════════════════════════════════════════╝"
          echo ""

      - name: 📝 Generate Next Cool Level (no ASCII)
        shell: bash
        run: |
          set -e

          cool_names=(
            "Vortex" "Nebula" "Phoenix" "Falcon" "Titan" "Shadow" "Blaze" "Nova" "Specter" "Stellar"
            "Inferno" "Cosmos" "Zephyr" "Obsidian" "Glacier" "Thunder" "Matrix" "Aurora" "Samurai" "Ninja"
            "Ronin" "Valkyrie" "Oracle" "Sonic" "Ranger" "Drift" "Mirage" "Cipher" "Echo" "Titanium"
            "Genesis" "Saber" "Onyx" "Blizzard" "Venom" "Storm" "Astro" "Galaxy" "Eclipse" "Magma"
            "Turbo" "Rogue" "Elemental" "Surge" "Radiant" "Zenith" "Prime" "Sentinel" "Golem" "Mystic"
          )

          mkdir -p levels

          last_name=""
          if ls levels/level-*-*.txt 1> /dev/null 2>&1; then
            last_file=$(ls levels/level-*-*.txt | sort | tail -n 1)
            last_name=$(basename "$last_file" | sed -E 's/level-[0-9]{8}-[0-9]{4}-(.*)\.txt/\1/')
          fi

          idx=0
          if [ -n "$last_name" ]; then
            for i in "${!cool_names[@]}"; do
              if [[ "${cool_names[$i]}" == "$last_name" ]]; then
                idx=$(( (i + 1) % ${#cool_names[@]} ))
                break
              fi
            done
          fi

          next_name="${cool_names[$idx]}"
          file_name="levels/level-$(date +%Y%m%d-%H%M)-${next_name}.txt"

          {
            echo "# 🌌 Level: $next_name"
            echo "# Generated at: $(date -u)"
            echo "# Dijalankan oleh: zayydenzi@gmail.com"
          } > "$file_name"

          echo "LEVEL_NAME=$next_name" >> $GITHUB_ENV
          echo "Created $file_name"

      - name: ⏰ Generate Formatted Time
        run: |
          echo "FORMATTED_TIME=$(TZ='Asia/Jakarta' date '+%d-%m-%Y %H:%M:%S WIB')" >> $GITHUB_ENV

      - name: 🔢 Generate Notification Counter
        id: notif-counter
        run: |
          count=$(ls levels/level-*-*.txt 2>/dev/null | wc -l)
          echo "NOTIF_COUNTER=$count" >> $GITHUB_ENV

      - name: 🔔 Send Notification to Telegram
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            <b>╔═════════════════════════════════════╗</b>
            <b>🎉⭐️🧡 LEVEL UNLOCKED! 🧡⭐️🎉</b>
            <b>✦✦✦ THE GATE TO GLORY OPENS ✦✦✦</b>
            <b>🚀🔥💎 NEW COOL LEVEL 💎🔥🚀</b>
            <b>✦✦✦ UNLEASH YOUR NEXT POWER! ✦✦✦</b>
            <b>╚═════════════════════════════════════╝</b>

            <pre>
╔════════════════════════════════════════════════╗
║ • 🎮 New Level:         ${{ env.LEVEL_NAME }}              
║ • 🗂️ Repository:        ${{ github.repository }}      
║ • 🕒 Time:              ${{ env.FORMATTED_TIME }}    
║ • 🔢 Notification No.:  ${{ env.NOTIF_COUNTER }}     
║ • 👤 Auto Commit By:    zayydenzi@gmail.com       
╚════════════════════════════════════════════════╝
            </pre>

            <b>#NextLevel</b>
            <b>💯 This script was 100% created by Abie Haryatmo</b>
          format: html

      - name: 🤖 Configure Git
        run: |
          git config user.name "zayydenzi"
          git config user.email "zayydenzi@gmail.com"

      - name: 🚩 Commit & Push Changes
        run: |
          git add levels/
          git commit -m "✨ Add Level: ${{ env.LEVEL_NAME }} (by zayydenzi@gmail.com)" || echo "Nothing to commit"
          git push
