name: 🚀 Auto Cultivation Level Generator & Weekly Winner

on:
  schedule:
    - cron: '*/15 * * * *'
    - cron: '0 0 * * 1'
  workflow_dispatch:

jobs:
  generate-level:
    if: github.event.schedule != '0 0 * * 1'
    name: 🌟 Generate Cultivation Level
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v4

      - name: ✨ Cultivation System Banner
        run: |
          echo ""
          echo "╔═══🌌══════════🌌═══╗"
          echo "    🐉SPIRIT VEINS AWAKENED🐉  "
          echo "  🏮IMMORTAL SEAL UNLOCKED🏮 "
          echo "    🍃QI FLOW HARMONIZED🍃  "
          echo "╚═══🌌══════════🌌═══╝"
          echo ""

      - name: 📝 Generate Next Cultivation Level
        shell: bash
        run: |
          set -e
          cultivation_levels=(
            "Qi Condensation"
            "Foundation Establishment"
            "Core Formation"
            "Nascent Soul"
            "Soul Formation"
            "Soul Transformation"
            "Ascendant"
            "Illusory Yin"
            "Corporeal Yang"
            "Nirvana Scryer"
            "Nirvana Cleanser"
            "Nirvana Shatterer"
            "Heaven's Blight"
            "Nirvana Void"
            "Profound Void (Spirit Void)"
            "Calamity Void (Arcane Void)"
            "Void Tribulant"
            "Half-step into Heaven (Half-Step Heaven Trampling)"
            "Step into the Heaven (Heaven Trampling)"
          )
          # Function to get cultivation level based on score
          get_cultivation_level() {
            local score=$1
            if ((score >= 1 && score <= 14)); then
              echo "Qi Condensation"
            elif ((score >= 15 && score <= 28)); then
              echo "Foundation Establishment"
            elif ((score >= 29 && score <= 42)); then
              echo "Core Formation"
            elif ((score >= 43 && score <= 56)); then
              echo "Nascent Soul"
            elif ((score >= 57 && score <= 70)); then
              echo "Soul Formation"
            elif ((score >= 71 && score <= 84)); then
              echo "Soul Transformation"
            elif ((score >= 85 && score <= 100)); then
              echo "Ascendant"
            elif ((score >= 101 && score <= 117)); then
              echo "Illusory Yin"
            elif ((score >= 118 && score <= 134)); then
              echo "Corporeal Yang"
            elif ((score >= 135 && score <= 151)); then
              echo "Nirvana Scryer"
            elif ((score >= 152 && score <= 168)); then
              echo "Nirvana Cleanser"
            elif ((score >= 169 && score <= 185)); then
              echo "Nirvana Shatterer"
            elif ((score >= 186 && score <= 200)); then
              echo "Heaven's Blight"
            elif ((score >= 201 && score <= 360)); then
              echo "Nirvana Void"
            elif ((score >= 361 && score <= 520)); then
              echo "Profound Void (Spirit Void)"
            elif ((score >= 521 && score <= 680)); then
              echo "Calamity Void (Arcane Void)"
            elif ((score >= 681 && score <= 840)); then
              echo "Void Tribulant"
            elif ((score >= 841 && score <= 1000)); then
              echo "Half-step into Heaven (Half-Step Heaven Trampling)"
            elif ((score >= 1001)); then
              echo "Step into the Heaven (Heaven Trampling)"
            else
              echo "Unranked"
            fi
          }

          mkdir -p levels
          # Example: get the user's score from leaderboard.json (default to 1 if not found)
          score=1
          if [ -f data/leaderboard.json ]; then
            user="${{ github.actor }}"
            score=$(jq -r --arg user "$user" '.[$user] // 1' data/leaderboard.json)
          fi
          LEVEL_NAME=$(get_cultivation_level $score)
          file_name="levels/level-$(date +%Y%m%d-%H%M)-${LEVEL_NAME}.txt"
          {
            echo "# Cultivation Level: $LEVEL_NAME"
            echo "# Generated at: $(date -u)"
            echo "# By: zayydenzi@gmail.com"
            echo "# Score: $score"
          } > "$file_name"
          echo "LEVEL_NAME=$LEVEL_NAME" >> $GITHUB_ENV
          echo "SCORE=$score" >> $GITHUB_ENV
          echo "Created $file_name"

      - name: ⏰ Generate Formatted Time
        run: |
          echo "FORMATTED_TIME=$(TZ
